require: rubocop-performance

inherit_from:
  - https://raw.githubusercontent.com/dramancompany/rubocop-drama/master/.rubocop_drama.yml

AllCops:
  TargetRubyVersion: 3.0.3
  TargetRailsVersion: 7.0.4
  NewCops: enable
  Exclude:
    - vendor/rbs/gem_rbs_collection/**/*
    - bin/**/*

Layout/LineLength:
  Exclude:
    - Gemfile

Metrics/BlockLength:
  Exclude:
    - config/environments/**/*
    - spec/**/*

Rails/HasManyOrHasOneDependent:
  Enabled: false
