name: Rails

on:
  - pull_request

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .tool-versions
          bundler-cache: true

      - name: Run Rubocop
        run: bundle exec rubocop

  rspec:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .tool-versions
          bundler-cache: true

      - name: Set up database
        run: bundle exec rails db:migrate RAILS_ENV=test

      - name: Run Rspec tests
        run: bundle exec rspec
